[CmdletBinding()]
param(
    [ValidateSet('Plan','Apply')][string]$Mode = 'Plan',
    [string]$VaultRoot = '',
    [string]$BackupPath = '',
    [string]$CodexHome = '',
    [string]$SkillsHome = '',
    [string]$LeanConfigPath = ''
)
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
if ([string]::IsNullOrWhiteSpace($VaultRoot)) { $VaultRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..')) }
if ([string]::IsNullOrWhiteSpace($CodexHome)) { $CodexHome = Join-Path $env:USERPROFILE '.codex' } else { $CodexHome = [IO.Path]::GetFullPath($CodexHome) }
if ([string]::IsNullOrWhiteSpace($SkillsHome)) { $SkillsHome = Join-Path $env:USERPROFILE '.agents\skills' } else { $SkillsHome = [IO.Path]::GetFullPath($SkillsHome) }
function Hash([string]$Path) { (Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant() }
function Read-Utf8([string]$Path) { [IO.File]::ReadAllText($Path) }
function Write-Utf8([string]$Path,[string]$Value) { [IO.File]::WriteAllText($Path,$Value,[Text.UTF8Encoding]::new($false)) }
function Backup-IfPresent([string]$Target,[string]$Backup,[string]$UserHome) { if(Test-Path -LiteralPath $Target){$relative=$Target.Substring($UserHome.Length).TrimStart('\');$copy=Join-Path $Backup $relative;New-Item -ItemType Directory -Force -Path (Split-Path -Parent $copy)|Out-Null;Copy-Item -LiteralPath $Target -Destination $copy -Force;return $copy};return $null }
$sourceSkills=Join-Path $VaultRoot 'vendor\maeos\curated\skills';$sourceReferences=Join-Path $VaultRoot 'vendor\maeos\curated\references';$referenceHome=Join-Path $CodexHome 'references\maeos'
$targets=@(Get-ChildItem -LiteralPath $sourceSkills -Directory|ForEach-Object{[pscustomobject]@{kind='skill';source=(Join-Path $_.FullName 'SKILL.md');target=(Join-Path $SkillsHome ($_.Name+'\SKILL.md'))}})
$targets+=@(Get-ChildItem -LiteralPath $sourceReferences -File|ForEach-Object{[pscustomobject]@{kind='reference';source=$_.FullName;target=(Join-Path $referenceHome $_.Name)}})
$profile=Join-Path $CodexHome 'agents\sol-advisor.toml';$config=Join-Path $CodexHome 'config.toml';$manifestPath=Join-Path $CodexHome 'maeos\INSTALL_MANIFEST.json'
$timestamp=(Get-Date).ToUniversalTime().ToString('yyyyMMddTHHmmssZ');$backup=if([string]::IsNullOrWhiteSpace($BackupPath)){Join-Path $CodexHome ('backups\MAEOS-v1-'+$timestamp)}else{[IO.Path]::GetFullPath($BackupPath)}
$previous=$null;if(Test-Path -LiteralPath $manifestPath){$previous=(Read-Utf8 $manifestPath)|ConvertFrom-Json}
$previousFiles=if($null -eq $previous){@()}else{@($previous.files)}
$changes=[Collections.Generic.List[object]]::new()
foreach($entry in $targets){
  if(Test-Path -LiteralPath $entry.target){$current=Hash $entry.target;$desired=Hash $entry.source;if($current -ne $desired){$known=$previousFiles|Where-Object { [string]$_.destination -eq $entry.target }|Select-Object -First 1;if($null -eq $known -or [string]$known.sha256 -ne $current){throw "INSTALL_REFUSES_LOCAL_DRIFT: $($entry.target)"};$changes.Add($entry)}}else{$changes.Add($entry)}
}
$profileText=if(Test-Path -LiteralPath $profile){Read-Utf8 $profile}else{''};$configText=if(Test-Path -LiteralPath $config){Read-Utf8 $config}else{''}
$profileDesired='Use Terra High as the native MAEOS writer, integration, and coordination lane for every non-Ox write; it remains subject to the root decision and one-writer lock.';$configOld='TOKEN-OPT-001-A7: owner-started Sol only; default children 0, maximum direct children 16, depth 1, no recursive spawning, no background continuation, no automatic fallback.';$configDesired='MAEOS-v1: owner-started Sol High; default children 0, normal readers 0..4, finite-task-graph bursts through 16, depth 1, one writer per target, no recursion, no background continuation, no automatic fallback.'
if(Test-Path -LiteralPath $profile){if(-not $profileText.Contains($profileDesired)){if($profileText.Contains('depth-one A7 routing and final acceptance') -or $profileText.Contains('Use Terra High only for an explicit integration-sensitive root decision')){$changes.Add([pscustomobject]@{kind='profile';source='managed merge';target=$profile})}else{throw "INSTALL_REFUSES_PROFILE_DRIFT: $profile"}}}
if(Test-Path -LiteralPath $config){if($configText.Contains($configOld)){$changes.Add([pscustomobject]@{kind='config';source='managed stale-hint merge';target=$config})}elseif(-not $configText.Contains($configDesired)){throw "INSTALL_REFUSES_CONFIG_DRIFT: $config"}}
$globalTarget=Join-Path $CodexHome 'AGENTS.md';$priorGlobal=$previousFiles|Where-Object { [string]$_.kind -eq 'global_agents' }|Select-Object -First 1
$globalExtension=Join-Path $CodexHome '.agents\PROJECT_POLICY.md';$priorExtension=$previousFiles|Where-Object { [string]$_.kind -eq 'global_extension' }|Select-Object -First 1
$accountCodexHome=Join-Path $env:USERPROFILE '.codex';$isAccountInstall=([IO.Path]::GetFullPath($CodexHome) -eq [IO.Path]::GetFullPath($accountCodexHome))
$accountBackup='C:\Users\adria\.codex\backups\MAEOS-v1-20260901T000000Z';$profileBaselineBackup=Join-Path $accountBackup '.codex\agents\sol-advisor.toml';$configBaselineBackup=Join-Path $accountBackup '.codex\config.toml';$leanBaselineBackup=Join-Path $accountBackup 'lean-ctx-config.toml';$globalBaselineBackup='C:\Users\adria\.codex\backups\TOKEN-OPT-001-A5-20260831T185420Z\AGENTS.md';$extensionBaselineBackup='C:\Users\adria\.codex\backups\TOKEN-OPT-001-A5-20260831T185420Z\PROJECT_POLICY.md'
$lean=if([string]::IsNullOrWhiteSpace($LeanConfigPath)){Join-Path $env:USERPROFILE '.config\lean-ctx\config.toml'}else{[IO.Path]::GetFullPath($LeanConfigPath)};$priorLean=$previousFiles|Where-Object { [string]$_.kind -eq 'lean_ctx_exact_allowance' }|Select-Object -First 1
$hooks=Join-Path $CodexHome 'hooks.json';$priorHooks=$previousFiles|Where-Object { [string]$_.kind -eq 'codex_hooks' }|Select-Object -First 1
$maeosVerificationScripts=@('D:\Documents\Codex\GitHub\gpt-context-vault\automation\codex-model-routing\inspect-codex-features.ps1','D:\Documents\Codex\GitHub\gpt-context-vault\automation\codex-model-routing\test-maeos-routing.ps1','D:\Documents\Codex\GitHub\gpt-context-vault\automation\codex-model-routing\test-maeos-install.ps1','D:\Documents\Codex\GitHub\gpt-context-vault\automation\codex-model-routing\verify-maeos.ps1','D:\Documents\Codex\GitHub\gpt-context-vault\automation\codex-model-routing\verify-token-optimization.ps1')
if(Test-Path -LiteralPath $hooks){$hooksText=Read-Utf8 $hooks;if((($isAccountInstall -and (Hash $hooks) -ne '226375248cb470fac3ea585bb9541962fcf9a9d98f95268d32cc8a20edd44344') -or -not $hooksText.Contains('hook codex-session-start') -or -not $hooksText.Contains('hook observe'))){throw 'INSTALL_REFUSES_HOOKS_DRIFT'}}
if($null -ne $previous){foreach($entry in @($previousFiles|Where-Object { @('profile','config','global_agents','global_extension','lean_ctx_exact_allowance','codex_hooks') -contains [string]$_.kind })){if((Test-Path -LiteralPath $entry.destination) -and ([string]$entry.sha256 -ne (Hash $entry.destination))){if([string]$entry.kind -eq 'codex_hooks' -and [string]$entry.sha256 -eq '16d406056b832a2f9c506a0191c6e37aa683134dfbf7083d9f46dab0b1fae77f' -and (Hash $entry.destination) -eq '226375248cb470fac3ea585bb9541962fcf9a9d98f95268d32cc8a20edd44344'){continue};if(([string]$entry.kind -eq 'config') -and ([string]$entry.sha256 -eq '41344795a48254ad50e053c6511bb91538ab49f1d6f44260b862d1ba36c07609') -and ((Hash $entry.destination) -eq 'cc0d00427dddbf53fc8cb8ab85d49a9aec5df1a8b331deb38128789bc0abfa20') -and ((Hash $globalExtension) -eq (Hash (Join-Path $VaultRoot 'governance\agents\extensions\global-codex.PROJECT_POLICY.md')))){continue};if(([string]$entry.kind -eq 'config') -and ([string]$entry.sha256 -eq '5a83b0376f4bf383e348c0054f3256770d4020a2d2da9afbb248ea7d088ca040') -and ((Hash $entry.destination) -eq '41344795a48254ad50e053c6511bb91538ab49f1d6f44260b862d1ba36c07609') -and ((Hash $globalExtension) -eq (Hash (Join-Path $VaultRoot 'governance\agents\extensions\global-codex.PROJECT_POLICY.md')))){continue};if([string]$entry.kind -eq 'global_agents' -and (Hash $entry.destination) -eq (Hash (Join-Path $VaultRoot 'AGENTS.md'))){continue};if([string]$entry.kind -eq 'global_extension' -and (Hash $entry.destination) -eq (Hash (Join-Path $VaultRoot 'governance\agents\extensions\global-codex.PROJECT_POLICY.md'))){continue};throw "INSTALL_REFUSES_LOCAL_DRIFT: $($entry.destination)"}}}
$priorConfig=$previousFiles|Where-Object { [string]$_.kind -eq 'config' }|Select-Object -First 1
$manifestNeedsUpdate=($null -eq $previous -or [int]$previous.schema_version -lt 3 -or ((Test-Path -LiteralPath $config) -and ($null -eq $priorConfig -or [string]$priorConfig.sha256 -ne (Hash $config))) -or ((Test-Path -LiteralPath $globalTarget) -and ($null -eq $priorGlobal -or [string]$priorGlobal.sha256 -ne (Hash $globalTarget))) -or ((Test-Path -LiteralPath $globalExtension) -and $null -eq $priorExtension) -or ((Test-Path -LiteralPath $lean) -and ($null -eq $priorLean -or [string]$priorLean.sha256 -ne (Hash $lean))) -or ((Test-Path -LiteralPath $hooks) -and ($null -eq $priorHooks -or [string]$priorHooks.sha256 -ne (Hash $hooks))))
$changeTargets=@($changes|ForEach-Object{[string]$_.target})
if($Mode -eq 'Plan'){
  [ordered]@{mode='Plan';codex_home=$CodexHome;managed_changes=@($changes|ForEach-Object target);manifest_update=$manifestNeedsUpdate;global_agents='MANAGED_BY_CANONICAL_SYNC_ONLY';backup='created only for Apply when files or manifest require update';real_codex_calls=0}|ConvertTo-Json -Depth 6;exit 0
}
if($changes.Count -eq 0 -and -not $manifestNeedsUpdate){[ordered]@{mode='Apply';status='NOOP';manifest=$manifestPath;real_codex_calls=0}|ConvertTo-Json;exit 0}
New-Item -ItemType Directory -Force -Path $backup|Out-Null
$backups=@{};foreach($change in $changes){$backups[$change.target]=Backup-IfPresent $change.target $backup $CodexHome};if(Test-Path -LiteralPath $manifestPath){$backups[$manifestPath]=Backup-IfPresent $manifestPath $backup $CodexHome}
foreach($entry in $targets){if($changeTargets -contains $entry.target){New-Item -ItemType Directory -Force -Path (Split-Path -Parent $entry.target)|Out-Null;Copy-Item -LiteralPath $entry.source -Destination $entry.target -Force}}
if($changeTargets -contains $profile){$next=$profileText.Replace('depth-one A7 routing and final acceptance','MAEOS-v1 profitable-delegation routing and final acceptance').Replace('at most 16 direct children','0..4 normal readers, graph-gated read-only bursts through 16 direct children').Replace('Use Terra Max only after an explicit Sol fallback/integration decision','Use Terra High as the native MAEOS writer, integration, and coordination lane for every non-Ox write; it remains subject to the root decision and one-writer lock.').Replace('Use Terra High only for an explicit integration-sensitive root decision, except HAU-USC frontend implementation where Terra Max is the sole writer.','Use Terra High as the native MAEOS writer, integration, and coordination lane for every non-Ox write; it remains subject to the root decision and one-writer lock.');Write-Utf8 $profile $next}
if($changeTargets -contains $config){Write-Utf8 $config ($configText.Replace($configOld,$configDesired))}
$files=@();foreach($entry in $targets){$post=Hash $entry.target;$files+=[ordered]@{kind=$entry.kind;source=$entry.source.Substring($VaultRoot.Length).TrimStart('\');source_sha256=(Hash $entry.source);destination=$entry.target;sha256=$post;pre_sha256=$null;status='PREEXISTENCE_UNPROVEN_PRESERVE_ON_ROLLBACK';backup_path=$null;rollback='preserve on rollback; original absence was not proven'}}
$managed=@($files)
if(Test-Path -LiteralPath $profile){$managed+=[ordered]@{kind='profile';source='managed Unicode-safe merge';destination=$profile;sha256=(Hash $profile);pre_sha256=if($isAccountInstall){'60ee3f66d199379e2f67e2a6a0845191b1e4696f7faaa654e1de021852177c93'}else{$null};status='UPDATED_BY_MAEOS_V1';backup_path=if($isAccountInstall){$profileBaselineBackup}else{$backups[$profile]};rollback='restore exact baseline backup'}}
if(Test-Path -LiteralPath $config){$managed+=[ordered]@{kind='config';source='managed stale-A7-hint merge';destination=$config;sha256=(Hash $config);pre_sha256=if($isAccountInstall){'1936760cf133260e61fb8b8e5c4a149fbf117b855dc9f48c8154f9f65be00b4c'}else{$null};status='UPDATED_BY_MAEOS_V1';backup_path=if($isAccountInstall){$configBaselineBackup}else{$backups[$config]};rollback='restore exact baseline backup'}}
if(Test-Path -LiteralPath $hooks){$managed+=[ordered]@{kind='codex_hooks';source='verified existing user SessionStart hooks preserved; canonical LeanCTX block makes cached emission idempotent';destination=$hooks;sha256=(Hash $hooks);pre_sha256=if($isAccountInstall){'226375248cb470fac3ea585bb9541962fcf9a9d98f95268d32cc8a20edd44344'}else{$null};status='PRESERVED_EXISTING_SESSIONSTART_HOOKS';backup_path=if($isAccountInstall){Join-Path $accountBackup '.codex\hooks.json'}else{$backups[$hooks]};rollback='preserve existing hooks; restore exact backup only if explicitly requested'}}
if(Test-Path -LiteralPath $globalTarget){$managed+=[ordered]@{kind='global_agents';source='AGENTS.md';source_sha256=(Hash (Join-Path $VaultRoot 'AGENTS.md'));destination=$globalTarget;sha256=(Hash $globalTarget);pre_sha256=if($isAccountInstall){'9134072db442fc8e838b07434849701f4885a9c831d0b50a747103bc24f437b6'}else{$null};status='UPDATED_BY_CANONICAL_SYNC';backup_path=if($isAccountInstall){$globalBaselineBackup}else{$null};rollback='restore exact sync baseline backup'}}
if(Test-Path -LiteralPath $globalExtension){$extensionSource=Join-Path $VaultRoot 'governance\agents\extensions\global-codex.PROJECT_POLICY.md';$managed+=[ordered]@{kind='global_extension';source='governance/agents/extensions/global-codex.PROJECT_POLICY.md';source_sha256=(Hash $extensionSource);destination=$globalExtension;sha256=(Hash $globalExtension);pre_sha256=if($isAccountInstall){'5a3dd6e710cca1251e8b706c5087fac0a61fdfda7b4ce6c5375a86692ad875ae'}else{$null};status='UPDATED_BY_CANONICAL_SYNC';backup_path=if($isAccountInstall){$extensionBaselineBackup}else{$null};rollback='restore exact sync baseline backup'}}
if(Test-Path -LiteralPath $lean){if($isAccountInstall -and (-not (Test-Path -LiteralPath $leanBaselineBackup) -or (Hash $leanBaselineBackup) -ne 'f0e31f6f99df94c930034c76c2189b4dfb6ea8f60a5f780b6989aaa365382e55')){throw 'INSTALL_REFUSES_MISSING_OR_INVALID_LEAN_ROLLBACK'};$managed+=[ordered]@{kind='lean_ctx_exact_allowance';source='exact MAEOS verification script paths only';allowlisted_scripts=$maeosVerificationScripts;destination=$lean;sha256=(Hash $lean);pre_sha256='F0E31F6F99DF94C930034C76C2189B4DFB6EA8F60A5F780B6989AAA365382E55';status='INSTALLED_OR_PRESERVED';backup_path=if($isAccountInstall){$leanBaselineBackup}else{$backups[$lean]};rollback='restore verified exact backup; no shell-security weakening'}}
New-Item -ItemType Directory -Force -Path (Split-Path -Parent $manifestPath)|Out-Null
$document=[ordered]@{schema_version=3;standard='MAEOS-v1';backup=$backup;files=$managed;managed_scope='skills, curated references, profile/config narrow merges, global managed sync receipt, exact LeanCTX allowance';later_edits='FAIL_CLOSED_ON_HASH_DRIFT';runtime_model_proof='UNRUN_FRESH_SESSION_REQUIRED';real_codex_calls=0};Write-Utf8 $manifestPath (($document|ConvertTo-Json -Depth 10)+"`n")
[ordered]@{mode='Apply';status='APPLIED';backup=$backup;manifest=$manifestPath;files=@($files).Count;real_codex_calls=0}|ConvertTo-Json
