[CmdletBinding()]
param([string]$VaultRoot = '',[string]$CodexHome = '')
Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
if ([string]::IsNullOrWhiteSpace($VaultRoot)) { $VaultRoot = [IO.Path]::GetFullPath((Join-Path $PSScriptRoot '..\..')) }
if ([string]::IsNullOrWhiteSpace($CodexHome)) { $CodexHome=Join-Path $env:USERPROFILE '.codex' }
function Assert-Case([bool]$Value,[string]$Name){if(-not $Value){throw "VERIFY_FAILURE: $Name"};Write-Output "PASS $Name"}
function Hash([string]$Path){(Get-FileHash -LiteralPath $Path -Algorithm SHA256).Hash.ToLowerInvariant()}
$manifestPath=Join-Path $CodexHome 'maeos\INSTALL_MANIFEST.json';Assert-Case (Test-Path -LiteralPath $manifestPath) 'install manifest exists';$manifest=([IO.File]::ReadAllText($manifestPath)|ConvertFrom-Json)
Assert-Case ([int]$manifest.schema_version -eq 3 -and [string]$manifest.standard -eq 'MAEOS-v1') 'manifest identity';Assert-Case ([string]$manifest.later_edits -eq 'FAIL_CLOSED_ON_HASH_DRIFT') 'manifest later-edit fail-closed policy';Assert-Case (Test-Path -LiteralPath $manifest.backup) 'manifest backup path exists'
foreach($file in @($manifest.files)){Assert-Case (Test-Path -LiteralPath $file.destination) ('managed destination exists: '+$file.kind);Assert-Case ((Hash $file.destination) -eq [string]$file.sha256) ('managed destination hash: '+$file.kind);Assert-Case (-not [string]::IsNullOrWhiteSpace([string]$file.rollback)) ('managed rollback classification: '+$file.kind);if([string]$file.source -like 'vendor\maeos\*'){$source=Join-Path $VaultRoot $file.source;Assert-Case (Test-Path -LiteralPath $source) ('managed source exists: '+$file.kind);Assert-Case ((Hash $source) -eq [string]$file.source_sha256) ('managed source hash: '+$file.kind)}}
Assert-Case (@($manifest.files|Where-Object{[string]$_.kind -eq 'skill'}).Count -eq 6) 'all six curated skills present';Assert-Case (@($manifest.files|Where-Object{[string]$_.kind -eq 'reference'}).Count -eq 3) 'all three curated references present'
$assets=@($manifest.files|Where-Object{[string]$_.kind -in @('skill','reference')});foreach($asset in $assets){Assert-Case ([string]$asset.status -eq 'PREEXISTENCE_UNPROVEN_PRESERVE_ON_ROLLBACK' -and $null -eq $asset.pre_sha256 -and $null -eq $asset.backup_path -and [string]$asset.rollback -like 'preserve on rollback*') ('asset rollback preserves unproven preexistence: '+$asset.kind)}
$profileEntry=$manifest.files|Where-Object{[string]$_.kind -eq 'profile'}|Select-Object -First 1;$configEntry=$manifest.files|Where-Object{[string]$_.kind -eq 'config'}|Select-Object -First 1;$globalEntry=$manifest.files|Where-Object{[string]$_.kind -eq 'global_agents'}|Select-Object -First 1;$extensionEntry=$manifest.files|Where-Object{[string]$_.kind -eq 'global_extension'}|Select-Object -First 1
Assert-Case ($null -ne $profileEntry -and [string]$profileEntry.pre_sha256 -eq '60ee3f66d199379e2f67e2a6a0845191b1e4696f7faaa654e1de021852177c93' -and (Test-Path -LiteralPath $profileEntry.backup_path)) 'profile exact baseline and backup';Assert-Case ($null -ne $configEntry -and [string]$configEntry.pre_sha256 -eq '1936760cf133260e61fb8b8e5c4a149fbf117b855dc9f48c8154f9f65be00b4c' -and (Test-Path -LiteralPath $configEntry.backup_path)) 'config exact baseline and backup';Assert-Case ($null -ne $globalEntry -and [string]$globalEntry.pre_sha256 -eq '9134072db442fc8e838b07434849701f4885a9c831d0b50a747103bc24f437b6' -and (Test-Path -LiteralPath $globalEntry.backup_path)) 'global AGENTS exact baseline and backup';Assert-Case ($null -ne $extensionEntry -and [string]$extensionEntry.pre_sha256 -eq '5a3dd6e710cca1251e8b706c5087fac0a61fdfda7b4ce6c5375a86692ad875ae' -and (Test-Path -LiteralPath $extensionEntry.backup_path)) 'global extension exact baseline and backup'
$profile=Join-Path $CodexHome 'agents\sol-advisor.toml';$config=Join-Path $CodexHome 'config.toml';$configText=[IO.File]::ReadAllText($config);$global=Join-Path $CodexHome 'AGENTS.md';$lean=Join-Path $env:USERPROFILE '.config\lean-ctx\config.toml'
$hooks=Join-Path $CodexHome 'hooks.json';$hookEntry=$manifest.files|Where-Object{[string]$_.kind -eq 'codex_hooks'}|Select-Object -First 1
Assert-Case ($null -ne $hookEntry -and [string]$hookEntry.pre_sha256 -eq '226375248cb470fac3ea585bb9541962fcf9a9d98f95268d32cc8a20edd44344' -and [string]$hookEntry.sha256 -eq '226375248cb470fac3ea585bb9541962fcf9a9d98f95268d32cc8a20edd44344' -and (Test-Path -LiteralPath $hookEntry.backup_path)) 'hooks exact preserved baseline and backup';$hooksText=[IO.File]::ReadAllText($hooks);Assert-Case ($hooksText.Contains('hook codex-session-start') -and $hooksText.Contains('hook observe') -and [string]$hookEntry.status -eq 'PRESERVED_EXISTING_SESSIONSTART_HOOKS') 'existing SessionStart hooks preserved';Assert-Case ($configText.Contains("hooks.json:session_start:0:0")) 'hook trust state remains present'
Assert-Case (([IO.File]::ReadAllText($profile)).Contains('MAEOS-v1 profitable-delegation routing') -and ([IO.File]::ReadAllText($profile)).Contains('0..4 normal readers')) 'desired Sol profile state';Assert-Case ($configText.Contains('MAEOS-v1: owner-started Sol High') -and -not $configText.Contains('TOKEN-OPT-001-A7:')) 'desired config state';Assert-Case ((Hash $global) -eq (Hash (Join-Path $VaultRoot 'AGENTS.md'))) 'global managed replica equals canonical';$leanText=[IO.File]::ReadAllText($lean);foreach($scriptName in @('inspect-codex-features.ps1','test-maeos-routing.ps1','test-maeos-install.ps1','verify-maeos.ps1','verify-token-optimization.ps1')){Assert-Case ($leanText.Contains($scriptName)) ('LeanCTX exact allowance: '+$scriptName)};$leanEntry=@($manifest.files|Where-Object{[string]$_.kind -eq 'lean_ctx_exact_allowance'}|Select-Object -First 1);Assert-Case (@($leanEntry.allowlisted_scripts).Count -eq 5 -and (Test-Path -LiteralPath $leanEntry.backup_path) -and (Hash $leanEntry.backup_path) -eq 'f0e31f6f99df94c930034c76c2189b4dfb6ea8f60a5f780b6989aaa365382e55') 'LeanCTX manifest records verified exact rollback'
[ordered]@{status='PASS';managed_files=@($manifest.files).Count;references=3;skills=6;config='MAEOS_V1_DESIRED_STATE';runtime_model_proof='UNRUN_FRESH_SESSION_REQUIRED';real_codex_calls=0}|ConvertTo-Json
